# Generated by Django 5.1.2 on 2024-10-18 09:56

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_imageonfeed_noteonfeed_school_userjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userprofile',
            name='phone_and_mail_as_key',
        ),
        migrations.RemoveField(
            model_name='imageonfeed',
            name='email',
        ),
        migrations.RemoveField(
            model_name='imageonfeed',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='noteonfeed',
            name='email',
        ),
        migrations.RemoveField(
            model_name='noteonfeed',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='oneononechat',
            name='sender_email',
        ),
        migrations.RemoveField(
            model_name='oneononechat',
            name='sender_phone_number',
        ),
        migrations.RemoveField(
            model_name='userjob',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='userjob',
            name='user',
        ),
        migrations.AddField(
            model_name='imageonfeed',
            name='image',
            field=models.BinaryField(default=b'\x08'),
        ),
        migrations.AddField(
            model_name='imageonfeed',
            name='user_profile',
            field=models.ForeignKey(default='ignore me', on_delete=django.db.models.deletion.CASCADE, to='chat.userprofile'),
        ),
        migrations.AddField(
            model_name='noteonfeed',
            name='user_profile',
            field=models.ForeignKey(default='ignore me', on_delete=django.db.models.deletion.CASCADE, to='chat.userprofile'),
        ),
        migrations.AddField(
            model_name='oneononechat',
            name='user_profile',
            field=models.ForeignKey(default='ignore me', on_delete=django.db.models.deletion.CASCADE, to='chat.userprofile'),
        ),
        migrations.AddField(
            model_name='school',
            name='user_profile',
            field=models.ForeignKey(default='ignore me', on_delete=django.db.models.deletion.CASCADE, to='chat.userprofile'),
        ),
        migrations.AddField(
            model_name='userjob',
            name='user_profile',
            field=models.ForeignKey(default='ignore me', on_delete=django.db.models.deletion.CASCADE, to='chat.userprofile'),
        ),
        migrations.AlterField(
            model_name='imageonfeed',
            name='uploaded_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddConstraint(
            model_name='school',
            constraint=models.UniqueConstraint(fields=('schook_title', 'start_time'), name='SchoolPK'),
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.UniqueConstraint(fields=('phone_number', 'email'), name='UserProfilePK'),
        ),
    ]
