# Generated by Django 5.1.2 on 2024-10-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_userprofile_phone_and_mail_as_key_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='school',
            name='SchoolPK',
        ),
        migrations.AddConstraint(
            model_name='school',
            constraint=models.UniqueConstraint(fields=('school_title', 'start_time'), name='SchoolPK'),
        ),
    ]
