# Generated by Django 5.1.2 on 2024-10-18 10:10

import chat.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_school_schoolpk_school_schoolpk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageonfeed',
            name='user_profile',
            field=models.ForeignKey(default=chat.models.get_default_user_profile, on_delete=django.db.models.deletion.CASCADE, to='chat.userprofile'),
        ),
        migrations.AlterField(
            model_name='noteonfeed',
            name='user_profile',
            field=models.ForeignKey(default=chat.models.get_default_user_profile, on_delete=django.db.models.deletion.CASCADE, to='chat.userprofile'),
        ),
        migrations.AlterField(
            model_name='oneononechat',
            name='user_profile',
            field=models.ForeignKey(default=chat.models.get_default_user_profile, on_delete=django.db.models.deletion.CASCADE, to='chat.userprofile'),
        ),
        migrations.AlterField(
            model_name='school',
            name='user_profile',
            field=models.ForeignKey(default=chat.models.get_default_user_profile, on_delete=django.db.models.deletion.CASCADE, to='chat.userprofile'),
        ),
        migrations.AlterField(
            model_name='userjob',
            name='user_profile',
            field=models.ForeignKey(default=chat.models.get_default_user_profile, on_delete=django.db.models.deletion.CASCADE, to='chat.userprofile'),
        ),
    ]
